### ISSUE TITLE
proj+heaven bug

### ISSUE THREAD

**Issue by jonlepage** [gameofbombs/pixi-heaven#10]
Hum cool feature but...
![heaven projs](https://user-images.githubusercontent.com/24865815/52926637-9c7f8780-3304-11e9-8b72-b718159506cd.gif)

this bug seems to happen in this context:

**parentContainer**: Container2d
**childDiffuse**: Sprite2d + spriteHeaven
**childNormal**: Sprite2d + spriteHeaven

**edit:**
i mean like this 
![image](https://user-images.githubusercontent.com/24865815/52934593-ed06dd00-3324-11e9-8a50-fb1bd67c992c.png)

**Comment by ivanpopelyshev** [comment]
nice! ha-ha

**Comment by jonlepage** [comment]
Is it caused by your last update in projection? Any solution. ?
I do not remember to see this bug before the last fix.

**Comment by jonlepage** [comment]
this one 
https://github.com/pixijs/pixi-projection/commit/abc1cc676d25eceaead448195a7407ce0c138d7f
or 
https://github.com/pixijs/pixi-projection/commit/76021c85ba27c09623b489ed409870601c8eb387
or
https://github.com/pixijs/pixi-projection/commit/7eef6dd93e08043595508dd3b8a7616386ed249d
sorry i dont know

**Comment by ivanpopelyshev** [comment]
Honestly, I don't know :)

What do you do exactly in those switches?

**Comment by jonlepage** [comment]
Ho OK so after tests in the debugger it seems **pluginName** the culpable.

If i convert the sprite2D in heaven with.
`sprite.convertToHeaven()`
the bug appears !

And after, if i try this
`sprite.pluginName = 'sprite2d';`
the bug disappears, but also heaven color.
So i think heaven it just not compatible with current projections setup ?.

I will try if i can just remove sprite2D nameSpace for childrens and use sprite2d for parent container only

**Comment by jonlepage** [comment]
work with just parent container as Sprite2d and i remove child `Sprite2d`, it fine for me thanks.

**Comment by jonlepage** [comment]
just to be shure am clear, here the visual @+
![image](https://user-images.githubusercontent.com/24865815/52941626-4415ad80-3337-11e9-82f6-2285a0aa373d.png)
