### ISSUE TITLE
Is there any plan for supporting v5?

### ISSUE THREAD

**Issue by rkdrnf** [gameofbombs/pixi-heaven#11]
I hope this plugin support v5 because I'm using this plugin a lot!
Is there any plan to support v5?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/pull/5706 - that's part of pixi-heaven, now it goes to v5. I will publish pixi-heaven for v5 as soon as this thing gets released.

What parts of heaven do you use, dark-light tint and masks?

**Comment by rkdrnf** [comment]
I use only dark-light tint. And I wander if there's any performance pitfall using both vanilla PIXI.Sprite and heaven.Sprite. Currently I'm using heaven.sprite for certain layer (using pixi-layers)

**Comment by ivanpopelyshev** [comment]
I didnt measure it, but theoretically it should be almost the same.

**Comment by rkdrnf** [comment]
Ok thanks for instant reply ivan!

**Comment by ivanpopelyshev** [comment]
Btw, dark-light tint and ColorMatrixFilter are look wrong without sRGB<->linear conversion. I want to add it in a month or two :)

**Comment by ivanpopelyshev** [comment]
@rkdrnf done.  two-tint works, masks are not.

**Comment by jjhesk** [comment]
so this heaven plugin can be basically import in babel and typescript environment in v5.1?

**Comment by ivanpopelyshev** [comment]
@jjhesk 

all typescript pixijs plugins have the same problem with ES6 imports: they require global PIXI:

```
import * as PIXI from "pixi.js";
global.PIXI = PIXI;
require("pixi-heaven "); //or import it
```

We dont have a way to build TS plugin that works both with vanilla JS and ES6 modules :(
