### ISSUE TITLE
question: performance

### ISSUE THREAD

**Issue by macguffin** [gameofbombs/pixi-heaven#12]
Hi Ivan you mention that this can effect performance. Anything in particular that is really bad?
Have you noticed a performance hit with polygon packing for example?

Thanks

**Comment by ivanpopelyshev** [comment]
No, i didnt measure anything here. Theoretically, fragment shader is a bit heavier. Also, if you start mixing standard pixi sprites with heaven sprites, there can be problem with batcher. Make sure your DC stays the same level as before and doesnt rise to 1000 :) Here is a tool to measure DC: https://github.com/eXponenta/gstatsjs

Summary: with this plugin, you have a few more ways to mess your app performance.
