### ISSUE TITLE
Regarding pixi-heaven for v5

### ISSUE THREAD

**Issue by msgopinath** [gameofbombs/pixi-heaven#13]
new PIXI.heaven.Spine(data) doesn't return spine object ? anything changed recently ?

**Comment by msgopinath** [comment]
Spine 3.7 implementation for PixiJS v5.

**Comment by ivanpopelyshev** [comment]
No, it should work. Give me more details :)

**Comment by msgopinath** [comment]
Previously when i use new PIXI.heaven.spine.Spine(data);
it return the spineObject i can access the pixi spine state skeleton and etc..

Now Am using PIXI Spine 3.7 implementation for PixiJS v5. Then updated PIXI-heaven v5 version.
this.spineObject = new PIXI.heaven.Spine(data);
this spineObject contains below not pixi spine state skeleton and etc.. 
"color: ColorTransform {dark: Float32Array(4), light: Float32Array(4), _updateID: 0, _currentUpdateID: -1, darkRgba: 0, …}
hasSpriteMask: false
__proto__: Spine"

**Comment by ivanpopelyshev** [comment]
I think you plugged in libs in wrong order.

https://github.com/gameofbombs/pixi-heaven#how-to-use-with-spine

Make sure that heaven is imported after pixi-spine. If you do it in separate files then I cant guarantee anything. Initialization order is super-important thing in heavy non-hello-world libs and ES6 import standard is very bad for coders of libraries :(

In case of vanilla, you have to <script src> in correct order.

**Comment by msgopinath** [comment]
Yes thats my bad the order is wrong and it din't complain , Now it works thanks

**Comment by ivanpopelyshev** [comment]
Well, that's why I'm answering in those repos =)
