### ISSUE TITLE
v5 pixi-heaven.d.ts file is empty

### ISSUE THREAD

**Issue by Jhsosa** [gameofbombs/pixi-heaven#15]
The types file pixi-heaven.d.ts. Anyway we can get the fully updated version?

**Comment by ivanpopelyshev** [comment]
oh, something is wrong.. you can compile it locally, i'll look in a few days.

**Comment by sntx** [comment]
Any updates on this...? pixi-heaven.d.ts is empty for me too, using version 0.2.1. Thank you!

**Comment by sntx** [comment]
@ivanpopelyshev Created pull request that fixes this issue: https://github.com/gameofbombs/pixi-heaven/pull/17
