### ISSUE TITLE
Incorrect rendering of spine mesh + blend additive, using pixi-heaven

### ISSUE THREAD

**Issue by a-rasinski** [gameofbombs/pixi-heaven#18]
There is some issue with rendering mesh sprite along with blend mode additive on it (that's the best conclusion I can give at the moment). Please see attached video - you can see spine animation played there with and without heaven plugin being enabled.

https://user-images.githubusercontent.com/25591650/109669755-b5b5a280-7b72-11eb-94e7-a57ac86d1f89.mp4

Affected spine asset: [Aliens.zip](https://github.com/gameofbombs/pixi-heaven/files/6069583/Aliens.zip)
Spine viewer used to demo the issue: https://d2yxcxpiisr7s0.cloudfront.net/
Feel free to check it yourself, just drag&drop zip with spine over the spine-viewer app.

Package versions affected by the issue (currently used in spine viewer):
```
"pixi-heaven": "0.2.2"
"pixi-spine": "2.0.5"
"pixi.js": "5.3.7"
```

Using pixi V4 with spine and heaven didn't produce mentioned issues, packages below:
```
"pixi-heaven": "0.1.21"
"pixi-spine": "1.5.22"
"pixi.js": "4.8.9"
```

**Comment by ivanpopelyshev** [comment]
Thank you for the production, I'll look at it :)

**Comment by a-rasinski** [comment]
@ivanpopelyshev Have you had a chance to take a look at this issue?

**Comment by ivanpopelyshev** [comment]
Not yet :( super busy

**Comment by ivanpopelyshev** [comment]
Done, now it should work.

0.2.3 👍 

also, it works with latest pixi-v6 now

**Comment by a-rasinski** [comment]
I can confirm that blending works nicely now. Thanks for the fix!
