### ISSUE TITLE
No dist/ folder 

### ISSUE THREAD

**Issue by TristanPct** [gameofbombs/pixi-heaven#21]
I tired to use the latest version (`v0.3.0`) but after `npm i --save pixi-heaven` the dependency folder (inside `node_modules/`) only contains:
- global.d.ts
- index.d.ts
- LICENSE
- package.json
- README.md

There is no `dist/` forder nor JS files.

I tried with yarn and different versions of npm.

**Comment by logaoleg** [comment]
I have the same issue :(

**Comment by ivanpopelyshev** [comment]
looking at it

**Comment by ivanpopelyshev** [comment]
publichsed 0.3.1 in npm, can you check please?

cant push in this repo because no rights :)

**Comment by logaoleg** [comment]
Checking

**Comment by logaoleg** [comment]
https://www.npmjs.com/package/pixi-heaven
v0.3.0 is still the last one
@ivanpopelyshev

**Comment by logaoleg** [comment]
`0.3.1` is available now and I see `dist` folder. Thank you!
