### ISSUE TITLE
sprite.color.alpha ?

### ISSUE THREAD

**Issue by jonlepage** [gameofbombs/pixi-heaven#3]
what are suppose do the alpha?
I trying to change the value but its not work !, It alway 1.
Should allowed and able to change this value?
Now I make slider, it really more easy for control coloration in pixi-haven with high precision.
![image](https://user-images.githubusercontent.com/24865815/37839831-d7388f48-2e91-11e8-8d18-d8930ee4f967.png)

**Comment by ivanpopelyshev** [comment]
its always 1? its a bug. is"element.color.alpha" is the same as "element.alpha"

**Comment by ivanpopelyshev** [comment]
Code seems fine: https://github.com/gameofbombs/pixi-heaven/blob/master/src/twotint/ColorTransform.ts#L76

**Comment by ivanpopelyshev** [comment]
Ok, so we have new demos: http://pixijs.io/examples/#/layers/normals.js and http://pixijs.io/examples/#/layers/lighting.js . You can see that sprites are rendered inside layer renderTexture and that texture is used for something else.

**Comment by jonlepage** [comment]
ok so you have bug, because in my side , when i try assign alpha, it alway reset to 1 !

**Comment by jonlepage** [comment]
look my log i change the slider to assign alpha
![image](https://user-images.githubusercontent.com/24865815/37843022-19306562-2e9a-11e8-9762-11ecafe274e4.png)
the  listener assign alpha, but when i try look in object resulta a 1 !
```javascript
        iziT.darkR.on("slide", function(value) {
            objSprite.color.alpha = value; objSprite.color.invalidate();// _updateID++
            console.log('asign alpha ', objSprite.color.alpha );
        });
```

**Comment by ivanpopelyshev** [comment]
and whats value there?

**Comment by jonlepage** [comment]
the arg **value** its the range result from data of slider  'min:0 and max:1'
I think the alpha in **sprite.color.alpha** 
collides with the **sprite.alpha**!
It's illogical, I'll investigate.

**Comment by jonlepage** [comment]
ho!!!! ok i read upper, ok its same ! ?
ok I understand, this value was misleading, I thought it was the strenge apply the darker.!

**Comment by jonlepage** [comment]
Ok thank i will take a look today on your demo 
Also a great demo here http://proclive.io/lights-in-pixi-js/ but old
