### ISSUE TITLE
dark tint doesn't work on meshes

### ISSUE THREAD

**Issue by st3v0** [gameofbombs/pixi-heaven#5]
We have a spine animation which has some mesh animations with tint black enabled. This doesn't seem to work at all with this latest build

**Comment by ivanpopelyshev** [comment]
It should work. I add `plane.color.setDark(1.0, 1.0, 1.0);` here and right sprite turns white: https://gameofbombs.github.io/examples-heaven/#/mesh/animation.js

**Comment by st3v0** [comment]
That's because you're generating a mesh manually in script. What about meshes created in spine. You're not overriding the `newMesh` method in Spine.ts so wouldn't spine use the default PIXI.mesh.Mesh which doesn't have your color fixes?

Unfortunately i'm unable to give an example of what i'm working on at the moment, however I do have an artist currently creating an example to show you whats happening, however it will take a little time.

**Comment by ivanpopelyshev** [comment]
Oh, right, just posted this in pixi-spine issue :) Can you rebuild heaven yourself?

**Comment by st3v0** [comment]
I could or i could just inject a fix and override your newMesh myself. 

I created the other issue in pixi-spine because I'm hoping this would become standard behaviour as part of that project. Rather than having a dependency on this project as well.

**Comment by ivanpopelyshev** [comment]
Ok, updated binaries, try it: https://github.com/gameofbombs/pixi-heaven/tree/master/dist

I think that the changes are too extensive to be part of pixi-spine plugin: https://github.com/gameofbombs/pixi-heaven/tree/master/src/twotint

**Comment by ivanpopelyshev** [comment]
It works! Also, meshes are batched with sprites by default now.
