### ISSUE TITLE
maskSprite emits GL ERROR when applied

### ISSUE THREAD

**Issue by rkdrnf** [gameofbombs/pixi-heaven#7]
I'm trying to convert masking as batch operation using pixi-heaven.

But below code which is almost same as that of in README, emits error 
` [.WebGL-0x7f87e084c200]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0`

```
        this.heartGauge.maskSprite = this.mask;
        this.heartGauge.pluginName = 'spriteMasked';
        this.mask.renderable = false;

        this.container.addChild(
            this.heartGauge,
            this.frame,
            this.mask
        );
```
`heartGauge` is a `PIXI.heaven.Sprite` and `mask` is a `PIXI.Sprite`. 

`container` is plain Pixi container

Plain PIXI mask works well with same mask texture.

My pixi version is v4.

Is there anything I'm missing?

**Comment by Dai696** [comment]
@Ivan I actually noticed this bug too...

I didn't wanna bother u with it at the time and since I was limited on time I couldn't spend too much time messing with it

spriteMasked gave me the same issue so I wasn't able to use it...

**Comment by ivanpopelyshev** [comment]
Yesm I broke it and spent three last days fixing it. I uploaded fix here: https://github.com/gameofbombs/pixi-heaven/tree/master/dist 

gonna make npm release now. 

Thank you, @rkdrnf for noticing that!

**Comment by Dai696** [comment]
Awesome Ivan!!!

I'll test it soon!

**Comment by ErikSom** [comment]
Had the same issue. Is solved with great help from @ivanpopelyshev!

**Comment by rkdrnf** [comment]
Thank you it now works!
